### PR TITLE
deprecate model_name

### LINKED ISSUE #315: chore/add hi_res_model_name to partition and deprecate model_name
This api param doesn't match the ones going to the library so we should just fix it.

### PR DESCRIPTION
**Pull request by Coniferish**
Closes #315
Replaces calls to unstructured that had `model_name` with `hi_res_model_name`. This PR should NOT be merged until after https://github.com/Unstructured-IO/unstructured/pull/2289 is merged in the unstructured repo.

### CODE REVIEW

**Comment by awalker4** [comment]
Feels good to be rid of that hack! I guess we can sit on this until 0.11.6 is published, and then bump unstructured in this pr.

**Comment by Coniferish** [comment]
The related PR in unstructured has been merged:
https://github.com/Unstructured-IO/unstructured/pull/2289

**Review by awalker4 — APPROVED** [review]

**Comment by Coniferish** [comment]
@awalker4, when I inspect the call to `partition` from within `general.pipeline_api()`, it is not the recently updated `partition` in unstructured that has `hi_res_model_name` as a parameter. I created a new virtual env and reinstalled, but I'm still seeing the same thing. I saw that you updated the unstructured requirement and see `unstructured[local-inference]==0.11.6` in base.txt, so I'm wondering if you might know what else might be happening.

**Comment by Coniferish** [comment]
> @awalker4, when I inspect the call to `partition` from within `general.pipeline_api()`, it is not the recently updated `partition` in unstructured that has `hi_res_model_name` as a parameter. I created a new virtual env and reinstalled, but I'm still seeing the same thing. I saw that you updated the unstructured requirement and see `unstructured[local-inference]==0.11.6` in base.txt, so I'm wondering if you might know what else might be happening.

@qued, would you have any insights into this? I'm trying to figure out why the failing test is returning `200` when it should be returning `400` given an invalid `hi_res_model_name`

**Pull request merged**
