### PR TITLE
chore(deps): bump unstructured to 0.10.25

### PR DESCRIPTION
**Pull request by awalker4**
Revert the workaround added in #285

### CODE REVIEW

**Review by cragwolfe — APPROVED** [review]
LGTM, but what is going on the test failure? did tables performance regress?

**Comment by yuming-long** [comment]
Oops my bad, there are regression on docker output brought by https://github.com/Unstructured-IO/unstructured/pull/1801 on [this change](https://github.com/Unstructured-IO/unstructured/pull/1801/files#diff-cad52203f72900cd7abe756eda28191a23ea5a4b8cd6bd3216ff701f3cb32e80R399) 
I didn't notice this since i saw the local output is better...

**Comment by cragwolfe** [comment]
OK, thanks for mentioning @yuming-long . 0.10.25 has other important changes, so let's update the test and create an issue to track fixing the regression.

**Comment by yuming-long** [comment]
issue to track table regression: https://github.com/Unstructured-IO/unstructured/issues/1853

**Pull request merged**
